unique_ids:
  forms: {telaUsuarios: HWAUQVWDFCBOX3RMEHCDDYZG4PG25VRS, planta_primeiro_andar: MG3O5B5G56IVGWHPQZHWDCLJ6RNTBLJQ,
    formCadastro: TWAZ7OMPCLJT6V7TTYIADQMZFZAFQMO3, homepageAdm.ambiente_popup: CQO4R5V6KXPYFJFJK5Q64US2MWN7CPZS,
    homepageAdm.dev_room: DFKGQ3LICK62O3GHNHR3NR5EIOOPLNNK, homepageAdm.dev_room.RowTemplate2: XVTJE2FN3V3N5NGR6EC743QDLYUWG6KB,
    marcacao_sala: GSBZZ6GORFDWQEUE7I6G57UPN75ERQFX, homepageLimpeza: RPPT2AG4ISZ5VGXGBYM5LL5DUNE2CWWH,
    emConstrucao: IC6YBUHE7NS25F36JNDGNCGGLSOQY2PM, limpeza_repeater_template: 23W7LFDADDICJYCWJC6MN3WJXOO3RH6I,
    homepageAdm.RowTemplate1: F2QO72N4FSFU33X4PANQBOOP67ZNLYN2, homepageAdm: GC3L6AVX67SPTDXD4X2G2NKNJDL23CXA,
    dev_form: 5VP2YR6KALEOOWCZQJVUPLDYZ2HQHXTL, homepageComum: UGPNN3AHKHPXYEQAVLLMF4MCOT27V5TI,
    RowTemplate3: 3CGOKDOFTJLKM5JEF2YC4BHU7BRKZ562, homepageAdm.warningsTemplate: CIR5ZJTLH5WMTMNLFBNB3PVLLW2WC6PS}
  modules: {}
  server_modules: {ServerModule1: LIUNWD2P5B4UPLDHORGNAQTECEIEYLQY}
  assets: {left-arrow.png: XJ7A6R6MHIGSKEOS4DMMIEZGJQLEENC7, broom-gray.png: D5S6RFFABJSS7MN3UAEGI3YS5ASBZ2DJ,
    users-group-gray.png: 32CDLB42KMFEYDMUGD4NMYEGMD2HJQTY, emconstrucao.jpg: IUACH5DAFJSIJMTUCPZ4CYUBY4GXN4DB,
    co2-cloud-gray.png: 77VS4465AFSAXZQ4LEWHUK2R7HXYPCNL, theme.css: JGXZSHJPNIRBCXLD6DT2M6UMQC5NGBGG,
    settings.png: L2YRAJQJKV5HAJPNWNIZBDEUETXAQ3IG, broom.png: SA3U3L2M7NLHZNRR5ICA6QNE6J4ZUCIG,
    standard-page.html: Z5MPSX4KSFFKZWPESNZIFYSEE6BSIDF3, co2-critico.png: FSL3DKRHHWC2YU6DO7FGH2J5PFGCJDML,
    ufrj-logo.jpg: 264NZA3FYED4R5WFEYP3HB57J5SCKDE2, 1_Andar_8000pixels.PNG: OSXWU7EHNXA2LJ5IJSPRP6HRVBHTT6EN,
    controls-green.png: UPANSKABVX7NJBBSRUGCFVLSRCA66DCX, controls-red.png: BMI7CJAFTSLBCUYH2KHQ65D5QWGGC3XF,
    right-arrow.png: UQRZQ72TVD5VYDC3WMWSN2EDXJ5G4I7H, red-circle.png: 5ZP6SKCQJEILYEXZ3ACXUABZWV2SH7MD,
    users-group.png: HNPWNYZURUDFHSVXXHPCGTDTDDBA2KWF, green-circle.png: LDNGG7QA46BTTR63ZTFCF45PKAUZCANX,
    overcapacity.png: 6SYGNDEREKIWRLCROR4YLHDP6DPKFJLS, yellow-circle.png: ZDCWW4MANHO5655ZMAR6SGZBBUQAKUCR,
    ok.png: 4O6W66DBMPTDZDBCTOJEC345ORYZMAOR, settings-gray.png: UHKAJDLBAIQTIJZIVAHDGMTR2DZEY4QY,
    clock.png: PIHETKLTLSDRJTE3HRELVIVXMEOFDQNU}
